### ISSUE TITLE
Move to https://github.com/blue-hats ?

### ISSUE THREAD

**Issue by bzg** [codegouvfr/helm-charts#2]
I suggest migrating this repo to https://github.com/blue-hats/ as the blue-hats organization account sounds more appropriate.

**Comment by garronej** [comment]
Hi @bzg,

This is a Helm repository of charts for application developers by @codegouv, not a general, reusable library of charts. I anticipated that there might have been more apps deployed using Helm, but in the end, there's only the SILL.

I'm not sure it makes sense to move it to Blue Hats since it's more for our internal use.

On top of that, note that the SILL is about to be deployed bare metal, so the Helm chart for SILL won't be actually used anymore.

**Comment by bzg** [comment]
Thanks.  I thought this repo was https://github.com/codegouvfr/awesome-bluehats-helm, which is a better candidate for moving to the `blue-hats` organization account, I'll follow-up there and I'm closing this issue.
